spring:
  profiles:
    include:
      - credential
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DB_URL}
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  mail:
    host: ${MAIL_SMTP}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME} # your email
    password: ${MAIL_PASSWORD} # your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    org.springframework.security: TRACE